project_id = "ijvhqqdfthchtittyvnt"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["https://ijvhqqdfthchtittyvnt.supabase.co"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
refresh_token_reuse_interval = 10
enable_signup = true
enable_anonymous_sign_ins = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[db]
port = 54322

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
port = 54323
ip_version = "ipv4"

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1:54321"

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
port = 54325
file_size_limit = "50MiB"
image_transformation = {"enabled": true}

[analytics]
enabled = false
port = 54327
vector_port = 54328
backend = "postgres"

[functions.analyze-competitor]
verify_jwt = true

[functions.generate-insights]
verify_jwt = true

[functions.openai-health]
verify_jwt = false

[functions.team-performance-report]
verify_jwt = false

[functions.team-performance-report-batch]
verify_jwt = false

[functions.send-report-email]
verify_jwt = true

[functions.process-scheduled-reports]
verify_jwt = false

[functions.get-report-share]
verify_jwt = false

[functions.advanced-media-processor]
verify_jwt = true

[functions.document-processor]
verify_jwt = true

[functions.content-analyzer]
verify_jwt = true

[functions.storage-lifecycle]
verify_jwt = true

[functions.cdn-manager]
verify_jwt = true

[functions.search-indexer]
verify_jwt = true

[functions.health-check]
verify_jwt = false

[functions.metrics]
verify_jwt = false

[functions.error-tracker]
verify_jwt = false

[functions.performance-collector]
verify_jwt = false

[functions.log-processor]
verify_jwt = false

[functions.system-health-monitor]
verify_jwt = false

[functions.cache-manager]
verify_jwt = false

[functions.security-monitor]
verify_jwt = false

[functions.audit-logger]
verify_jwt = false
